# Generated by Django 6.0.3 on 2026-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], db_index=True, default='pending', max_length=20),
        ),
    ]
