# Generated by Django 6.0.3 on 2026-03-06 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('image', 'Image Upgrade'), ('k8s', 'K8s Upgrade')], max_length=10)),
                ('image_url', models.CharField(blank=True, help_text='For image upgrade: full image URL', max_length=500)),
                ('target_version', models.CharField(blank=True, help_text='For k8s upgrade: target version e.g. 1.32.0', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_jobs', to='clusters.cluster')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_nodes', models.ManyToManyField(blank=True, related_name='upgrade_jobs', to='clusters.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
