# Generated by Django 6.0.3 on 2026-03-06 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('endpoint', models.CharField(help_text='e.g. https://192.168.1.10:50000', max_length=500)),
                ('talosconfig_content', models.TextField(help_text='Paste your talosconfig YAML here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('controlplane', 'Control Plane'), ('worker', 'Worker')], default='worker', max_length=20)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('talos_version', models.CharField(blank=True, max_length=50)),
                ('k8s_version', models.CharField(blank=True, max_length=50)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='clusters.cluster')),
            ],
            options={
                'ordering': ['role', 'ip_address'],
                'unique_together': {('cluster', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='NodeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('reboot', 'Reboot'), ('shutdown', 'Shutdown'), ('reset', 'Reset'), ('restart_service', 'Restart Service')], max_length=30)),
                ('service_name', models.CharField(blank=True, help_text='For restart_service only', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='clusters.node')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
